### PR TITLE
fix: make map center effective

### LINKED ISSUE #186: bug: center of map not effective
I found the center of the map is always fixed at one point by default, even though there is no data point there.

Then I found the problem might be caused by this https://stackoverflow.com/questions/64665827/react-leaflet-center-attribute-does-not-change-when-the-center-state-changes

Therefore, the `center` state here may not be effective when its value changes
https://github.com/Kanaries/graphic-walker/blob/81009e98079370f4f26987555c30690cce3d1d90/packages/graphic-walker/src/components/leafletRenderer/POIRenderer.tsx#L139

### PR DESCRIPTION
**Pull request by islxyqwe**
resolves #186

add ChangeView component metioned in #186 ,and fixes the wrong bounds calculation.

https://github.com/Kanaries/graphic-walker/assets/15280968/f7fbccf3-ce26-41ba-8140-2efe22004552

### CODE REVIEW

File: packages/graphic-walker/src/components/leafletRenderer/utils.ts [hunk 1]
```diff
@@ -50,3 +51,10 @@ export const useDisplayValueFormatter = (semanticType: ISemanticType, vegaConfig
     }, [semanticType, numberFormatter, timeFormatter]);
     return formatter;
 };
+
+export function ChangeView({ bounds }) {
+    const map = useMap();
+    console.log(bounds);
```
Comment (ObservedObserver) [inline packages/graphic-walker/src/components/leafletRenderer/utils.ts:57]: ?

File: packages/graphic-walker/src/components/leafletRenderer/utils.ts [hunk 2]
```diff
@@ -50,3 +51,10 @@ export const useDisplayValueFormatter = (semanticType: ISemanticType, vegaConfig
     }, [semanticType, numberFormatter, timeFormatter]);
     return formatter;
 };
+
+export function ChangeView({ bounds }) {
```
Comment (ObservedObserver) [inline packages/graphic-walker/src/components/leafletRenderer/utils.ts:55]: ?

**Review by ObservedObserver — CHANGES_REQUESTED** [review]

File: packages/graphic-walker/src/components/leafletRenderer/utils.ts (hunk 1 above)
Comment (ObservedObserver) [reply packages/graphic-walker/src/components/leafletRenderer/utils.ts]: fix the types

**Review by ObservedObserver — APPROVED** [review]
